exports.DEFAULT_ERROR = 'DEFAULT_ERROR';
exports.SERVER_ERROR = 'SERVER_ERROR';
exports.SCHEMA_ERROR = 'SCHEMA_ERROR';
exports.UNAUTHORIZED = 'UNAUTHORIZED';
exports.BAD_REQUEST = 'BAD_REQUEST';
exports.NOT_FOUND = 'NOT_FOUND';
exports.DATABASE_ERROR = 'DATABASE_ERROR';
